// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseAdminClient() {
  const SUPABASE_URL = process.env.SUPABASE_URL?.trim();
  const SUPABASE_SERVICE_ROLE_KEY =
    process.env.SUPABASE_SERVICE_ROLE_KEY?.trim() ||
    process.env.SERVICE_ROLE_KEY?.trim() ||
    process.env.SUPABASE_SERVICE_KEY?.trim() ||
    process.env.SERVICE_SUPABASEANON_KEY?.trim() ||
    process.env.SELFHOST_SUPABASE_SERVICE_KEY?.trim() ||
    process.env.SERVICE_SUPABASESERVICE_KEY?.trim();

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  if (SUPABASE_SERVICE_ROLE_KEY.startsWith('eyJ')) {
    const [, payload] = SUPABASE_SERVICE_ROLE_KEY.split('.');
    try {
      const decoded = JSON.parse(Buffer.from(payload ?? '', 'base64url').toString('utf8')) as { role?: string };
      if (decoded.role && decoded.role !== 'service_role') {
        throw new Error(
          `SUPABASE_SERVICE_ROLE_KEY must be the service_role key, but the configured key role is "${decoded.role}".`,
        );
      }
    } catch (error) {
      if (error instanceof Error && error.message.includes('configured key role')) throw error;
      throw new Error('SUPABASE_SERVICE_ROLE_KEY is not a valid Supabase service-role JWT.');
    }
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
    global: {
      fetch: (input, init) => {
        const headers = new Headers(init?.headers);
        if (
          SUPABASE_SERVICE_ROLE_KEY.startsWith('sb_') &&
          headers.get('Authorization') === `Bearer ${SUPABASE_SERVICE_ROLE_KEY}`
        ) {
          headers.delete('Authorization');
        }
        headers.set('apikey', SUPABASE_SERVICE_ROLE_KEY);
        return fetch(input, { ...init, headers });
      },
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
